### ISSUE TITLE
SES - Enhancement request: switch to latest Aws ZF2 module

### ISSUE THREAD

**Issue by jackdpeterson** [juriansluiman/SlmMail#90]
It appears that this is presently undocumented so I'll at least list this as an issue. This module depends on the older version of the AWS ZF2 module and not on the latest version.

Converting to a newer version looks to be as simple as modifying SesServiceFactory to:
```
namespace SlmMail\Factory;

use SlmMail\Service\SesService;
use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use Aws\Sdk;

class SesServiceFactory implements FactoryInterface
{

    /**
     *
     * {@inheritDoc}
     *
     */
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        return new SesService($serviceLocator->get(Sdk::class)->createSes());
    }
}
```

Is this something that is planned in the near future? I realize that this may also affect other modules like SlmQueue and should probably be committed in parallel for projects that depends on both SlmQueue as well as SlmMail.

**Comment by bakura10** [comment]
Hi,

Definitely! As you said the issue is mostly that we need to coordinate the update of all modules (as it's not possible to use differnet versions of the same library).

For SlmQueue the code is actually ready (I've suggested bumping the version just to be able to update all the modules). Then we need to update this one.

Could you please provide a PR for SlmMail ?

**Comment by jackdpeterson** [comment]
Gladly. If I have some time this evening, I'll put that together. if not tonight, then tomorrow :-)

**Comment by jackdpeterson** [comment]
okay, now that the commit has been squashed...

**Comment by jackdpeterson** [comment]
I'm not sure if this will pass your build test as I'm not seeing where the reference to the AwsModule is defined to make that change in testing; howver, I've added an additional commit and squashed changes to make the reference change in composer.json's require-dev.

**Comment by jackdpeterson** [comment]
The newest version of AWS ZF2 SDK module appears to require a minimum PHP version of 5.5.

**Comment by bakura10** [comment]
Damn... I think it would be good to upgrade this module minimum version to PHP 5.5 anyway, as the main framework do so. @juriansluiman ?

**Comment by juriansluiman** [comment]
@bakura10 +1. Create a v1.6 or v2.0 with php 5.5+ and if using php < 5.5 then you're stuck to v1.5.3 for now. If ppl really needs features from the v1.6/v2.0 branch we could always backport them into v1.5.3 if needed.

**Comment by bakura10** [comment]
I'd like to tag v1.6 (instead of v2), so we can keep the v2 for "the future" (we'll likely need how we can remove the dependency to ZF module I suppose...). But isn't the bump to PHP 5.5 a BC? I remember that @ocramius told a thing about that not being a complete BC break that didn't require a new major version, but I can't remember the exact reason.

**Comment by jackdpeterson** [comment]
new commit for PR is submitted above. commits were squashed for consistency / easy of integration. Tagging will be on your end though I believe. Also, I'm not sure about and travisCI integration details.

**Comment by kersten** [comment]
are their any timelines when this will be implemented?

**Comment by jackdpeterson** [comment]
I'll take a look at this tomorrow and see if I can't get the travis builds passing.
